# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('intro', models.TextField(default='', max_length=1024)),
                ('img_index', models.TextField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('intro', models.TextField(default='', max_length=256)),
                ('img_index', models.CharField(default='', max_length=64)),
                ('img_detail_index', models.TextField(default='', max_length=256)),
                ('img_detail_arg', models.TextField(default='', max_length=256)),
                ('img_detail_detail', models.TextField(default='', max_length=256)),
            ],
        ),
    ]
